version: "3.9"

services:
  web:
    image: example-01:latest
    restart: always
    ports:
      - 9001:9001

  # container for database backing wordpress
  # wordpress_db:

  # container for wordpress server
  # wordpress:

  # container for reverse proxy server
  # reverse-proxy:
# volumes:
