# Provide the base image
# FROM

# Copy local files into the image
# COPY

# Run any necessary commands to prepare files, generate assets, etc.
# RUN

# Label ports for exposure
# EXPOSE

# Define the command which starts the container
# CMD