apiVersion: v1
kind: Service
metadata:
  name: example-rails-service
spec:
  type: LoadBalancer
  selector:
    app: example-rails
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
